name: ttyd-pro
adopt-info: ttyd-pro
summary: Mobile-first terminal sharing over the web
description: |
 ttyd-pro embeds a mobile-first terminal UI, virtual keyboard, tabs, and
 image-paste support in a single ttyd-compatible binary.

grade: stable
confinement: classic
base: core20
compression: lzo

license: MIT

assumes:
  - command-chain

apps:
  ttyd-pro:
    command: usr/bin/ttyd
    command-chain: 
      - bin/homeishome-launch       

parts:
  ttyd-pro:
    source: https://github.com/vannguyen799/ttyd-pro
    source-type: git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-environment:
      - LDFLAGS: "-pthread"
      
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - build-essential 
      - libjson-c-dev 
      - libwebsockets-dev
      
    stage-packages:
      - libjson-c4
      - libwebsockets15
      
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch  
